version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SECRET_KEY=${SECRET_KEY}

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app_network
    depends_on:
      - backend
    environment:
      - VITE_URL=${VITE_URL}

networks:
  app_network:
    driver: bridge
